[package]
name = "vulkano_lab"
version = "0.1.0"
edition = "2024"

[lib]
name = "vulkano_lab"
crate-type = ["cdylib","lib"]

[dependencies]
image = "0.25.9"
vulkano = "0.35.2"
jni = "0.21.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.dev]
opt-level = 1